# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven, tests and documentation generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
           
    - name: Install doxygen
      run: sudo apt-get install -y doxygen
      
    - name: Install graphviz
      run: sudo apt-get install -y graphviz
      
    - name: Test with Maven
      run: mvn test -DargLine="-Dcontiperf.active=false"
      
    - name: Prepare database for integration tests
      run: | 
        sudo /etc/init.d/mysql start
        mysql -uroot -proot < src/main/resources/database.sql
        mvn --batch-mode --update-snapshots compile 
        mvn --batch-mode --update-snapshots datanucleus:enhance
        mvn --batch-mode --update-snapshots datanucleus:schema-create
        mvn --batch-mode --update-snapshots exec:java -Pdatos
    - name: Build with Maven including integration tests
      run: mvn --batch-mode --update-snapshots verify -Pintegracion
      
    - name: Generate documentation
      run: mvn doxygen:report
      
    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: target/doxygen/html
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
